
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development: &development
  <<: *default
  database: tatame-back-api_development
  username: postgres
  password: tatame
  host: localhost

test:
  <<: *development
  database: bookstore-backend_test

production:
  <<: *default
  database: tatame-back-api_production
  username: tatame-back-api
  password: <%= ENV['TATAME-BACK-API_DATABASE_PASSWORD'] %>


